export const LOGIN_AUTH_REQUEST = "LOGIN_AUTH_REQUEST";
export const LOGIN_AUTH_SUCCESS = "LOGIN_AUTH_SUCCESS";
export const LOGIN_AUTH_FAILURE = "LOGIN_AUTH_FAILURE";
export const REGISTER_AUTH_REQUEST = "REGISTER_AUTH_REQUEST";
export const REGISTER_AUTH_SUCCESS = "REGISTER_AUTH_SUCCESS";
export const REGISTER_AUTH_FAILURE = "REGISTER_AUTH_FAILURE";
export const ADD_RECIPE_REQUEST = "ADD_RECIPE_REQUEST";
export const ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS";
export const GET_ALL_RECIPE_REQUEST = "GET_ALL_RECIPE_REQUEST";
export const GET_ALL_RECIPE_SUCCESS = "GET_ALL_RECIPE_SUCCESS";
export const GET_ALL_RECIPE_FAILURE = "GET_ALL_RECIPE_FAILURE";
export const GET_ALL_RECIPE_BY_CATEGORY_REQUEST =
  "GET_ALL_RECIPE_BY_CATEGORY_REQUEST";
export const GET_ALL_RECIPE_BY_CATEGORY_SUCCESS =
  "GET_ALL_RECIPE_BY_CATEGORY_SUCCESS";
export const GET_ALL_RECIPE_BY_CATEGORY_FAILURE =
  "GET_ALL_RECIPE_BY_CATEGORY_FAILURE";
export const GET_ALL_RECIPE_BY_ID_REQUEST = "GET_ALL_RECIPE_BY_ID_REQUEST";
export const GET_ALL_RECIPE_BY_ID_SUCCESS = "GET_ALL_RECIPE_BY_ID_SUCCESS";
export const GET_ALL_RECIPE_BY_ID_FAILURE = "GET_ALL_RECIPE_BY_ID_FAILURE";
